/* Todo.txt format used by TodoTxtJS */
Todo ::= CompletedFlag? CreateDate? Priority? Content

/* Definitions */
CompletedFlag ::= 'x' Space CompleteDate Space
CompleteDate ::= Date Space
Priority ::= '('[A-Z]')' Space
CreateDate ::= Date Space
Date ::= yyyy '-' mm '-' dd
Content ::= (Text | Context | Project | DueDate | Metadata)+
Context ::= '@' Token
Project ::= '+' Token
DueDate ::= 'due:' date
Metadata ::= MetadataName ':' MetadataValue

MetadataValue ::= Token
MetadataName ::= [A-Za-z0-9_] Token

Token ::= [^\s]*[A-Za-z0-9_]
Text ::= .*
yyyy ::= [0-9][0-9][0-9][0-9]
mm ::= ('0'[0-9]) | ('1'[0-2])
dd ::= ([0-2][0-9]) | ('3'[01])