import {Item} from './../models/item';

export const TODOS = [
    Item.parseString("This is a test file that implements examples for almost all features. Use with \"import/export\" to test the application."),
    Item.parseString("(A) Priority A"),
    Item.parseString("(B) Priority B"),
    Item.parseString("(C) Priority C"),
    Item.parseString("(D) Priority D"),
    Item.parseString("(E) Priority E"),
    Item.parseString("(F) Priority Other"),
    Item.parseString("A simple todotxt file for testing TodoTxtJs features"),
    Item.parseString("A todo with @context"),
    Item.parseString("A todo with +project"),
    Item.parseString("A todo with different case @Context"),
    Item.parseString("A todo with different case +Project"),
    Item.parseString("(A) Priority A due:today"),
    Item.parseString("(B) Priority B due:today"),
    Item.parseString("(C) Priority C due:today"),
    Item.parseString("2013-01-01 Todo with create date"),
    Item.parseString("Todo with due date: due:2013-01-01"),
    Item.parseString("Todo due Tomorrow: due:tomorrow"),
    Item.parseString("Todo due Today: due:today"),
    Item.parseString("Single character meta-data a:b as an example"),
    Item.parseString("Todo due Yesterday: due:yesterday"),
    Item.parseString("Todo due Monday: due:monday"),
    Item.parseString("Todo due Sunday: due:wed"),
    Item.parseString("Todo with metadata meta:data key:value"),
    Item.parseString("Todo with funky metadata v:1.2.3"),
    Item.parseString("Todo URL http://example.com/hello/there/world"),
    Item.parseString("2013-01-01 A todo with @every-thing +kitchen-sink http://example.com/hello/there/world due:2013-01-01"),
    Item.parseString("x 2013-01-01 2013-01-01 A todo with @every-thing +kitchen-sink http://example.com/hello/there/world due:2013-01-01"),
    Item.parseString("x 2013-01-01 (E) Completed todo"),
    Item.parseString("tämä on todo @kynällä"),
    Item.parseString("tämä on toinen todo +päivällä"),
    Item.parseString("tämä on kolmas todo @yöllä"),
    Item.parseString("2013-01-01 A todo with url with parentheses http://example.com/hello/t(her)e/world due:2013-01-01")
];